import { WidgetsGrid } from "@/components";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dashboard Main",
  description: "Generated by create next app",
};
export default function MainPage(){
    return(
     <div className="text-black p-2">
        <h1 className="mt-2 text-3xl">Dashboard</h1>
        <span className="}text-xl">Informacion General</span>
        <WidgetsGrid/>
     </div>
    )
}